# Generated by Django 6.1.1 on 2026-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_due_date_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('personal', 'Personal'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
