# Generated by Django 6.1.1 on 2026-09-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
